### ISSUE TITLE
pdsc files for PE_KSDK and Utility packs fail schema check

### ISSUE THREAD

**Issue by edriouk** [ErichStyger/McuOnEclipse_CMSIS-PACKS#1]
Hi Erich,
You pdsc files fail schema check: 
![mcuoneclipseschemacheck](https://cloud.githubusercontent.com/assets/10760440/13140843/ad1999f8-d634-11e5-962f-d35e5274d7bb.png)

The reason is that you have placed RTE_Components_h section on package level. It should be on component level (every component can have such section). 

Best regards,
Evgueni

**Comment by ErichStyger** [comment]
Hi Evgueni,
many thanks for pointing out that the XML files were not conforming to the schemata. I have not 'programmed' much XML, and I have missed that part about XML verification. I wrongly assumed that this would be part of the batch file. So I'm now using an XML checker (http://mcuoneclipse.com/2016/02/20/xml-editor-checker-for-cmsis-pack-in-eclipse/) :-) and I have fixed that problem. I have to do a test run and will commit/push the new files shortly.

Thanks!
Erich

**Comment by ErichStyger** [comment]
Hi Evgueni,
I can now confirm that you are correct and I was wrong: it works now for me too without the dependency. I have updated the article and pushed my changes. Thanks for having a look on this and getting me back on track!
Erich
